inboundShippingPerPound: .50

log: false

maxLargeStandardWeight: 20
maxLargeStandardDimensions:
       - 18
       - 14
       - 8

maxSmallStandardMediaWeight: 0.875
maxSmallStandardNonMediaWeight: .75
maxSmallStandardDimensions:
  - 15
  - 12
  - .75

maxSmallOversizeWeight: 70
maxSmallOversizeDimensions:
  - 60
  - 30
